# Generated by Django 4.2.4 on 2023-11-02 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('firstname', models.CharField(max_length=2000)),
                ('lastname', models.CharField(max_length=2000)),
                ('othernames', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=1000)),
                ('gpa', models.FloatField()),
                ('address', models.CharField(max_length=3000)),
                ('country', models.CharField(max_length=3000)),
                ('mobile', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
